#@替换位于line13 的cookie 和 line8 的 SCKEY
# cookie为吾爱论坛的cookie，自行抓取
# SCKEY为酷推推送的SKEY
import requests
import re

def pushinfo(info):
    requests.session().get("https://push.xuthus.cc/send/SCKEY?c=" +'吾爱论坛每日打卡通知'+ '\n'+info )


def main(*args):
    headers={
        'Cookie': 'htVD_2132_saltkey=SF6t40QF; htVD_2132_lastvisit=1614262687; Hm_lvt_46d556462595ed05e05f009cdafff31a=1612321430,1614264069,1614264234,1614266285; htVD_2132_seccodecSAnrLXie=7394953.25bd0c1dc63b8fce23; htVD_2132_seccodecSAnrL=7394952.47676eb7cc96cdf6b2; htVD_2132_con_request_uri=https%3A%2F%2Fwww.52pojie.cn%2Fconnect.php%3Fmod%3Dlogin%26op%3Dcallback%26referer%3Dhttps%253A%252F%252Fwww.52pojie.cn%252Fhome.php%253Fmod%253Dspace%2526username%253DReheart; htVD_2132_client_created=1614266298; htVD_2132_client_token=8BB04BB6A4EDAA6DB5E0AEF3856D2D12; htVD_2132_ulastactivity=1614266298%7C0; htVD_2132_auth=95542ax2eIo%2FGJSITgsHBoMgJxM183pVdd6p6%2BDAXyyCmqUT6hnNSP9ENlflxnZT7ZFOe6ylF88w8izgtzWWb20yopM%2B; htVD_2132_connect_login=1; htVD_2132_connect_is_bind=1; htVD_2132_connect_uin=8BB04BB6A4EDAA6DB5E0AEF3856D2D12; htVD_2132_stats_qc_login=3; htVD_2132_sid=0; htVD_2132_checkpm=1; htVD_2132_lastcheckfeed=1591656%7C1614266299; htVD_2132_checkfollow=1; htVD_2132_lastact=1614266300%09home.php%09space; Hm_lpvt_46d556462595ed05e05f009cdafff31a=1614266298' ,
        'ContentType':'text/html;charset=gbk'
    }
    requests.session().get('https://www.52pojie.cn/home.php?mod=task&do=apply&id=2',headers=headers)
    a=requests.session().get('https://www.52pojie.cn/home.php?mod=task&do=draw&id=2',headers=headers)
    print(a.text)
    c=re.findall('<p>(.*)</p>',a.text)
    c=c[0]
    print(c)


    if "您需要先登录才能继续本操作"  in c:
        pushinfo("Cookie失效")
    elif "恭喜"  in c:
        pushinfo("吾爱破解签到成功")
    elif "不是进行中的任务" in c:
        pushinfo("今天已经签过到了！")
        pass
    else :
        pushinfo("吾爱破解签到失败！")
    print(c)


def main_handler(event, context):
    main()

if __name__ == '__main__':
    main()
